-- Phase 9: menu analytics and customer orders.
-- Run once in the Supabase SQL editor after the base schema.

create table if not exists menu_visits (
  id uuid primary key default gen_random_uuid(), restaurant_id uuid not null references restaurants(id) on delete cascade,
  session_key text not null, visited_on date not null default current_date, created_at timestamptz not null default now(),
  unique (restaurant_id, session_key, visited_on)
);
create table if not exists orders (
  id uuid primary key default gen_random_uuid(), restaurant_id uuid not null references restaurants(id) on delete cascade,
  order_number bigint generated by default as identity, public_token uuid not null default gen_random_uuid() unique,
  idempotency_key uuid not null, customer_name text not null, customer_phone text, customer_note text,
  status text not null default 'pending' check (status in ('pending','confirmed','preparing','ready','completed','cancelled')),
  currency text not null, subtotal numeric(12,2) not null check (subtotal >= 0), total numeric(12,2) not null check (total >= 0),
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique (restaurant_id, idempotency_key)
);
create table if not exists order_items (
  id uuid primary key default gen_random_uuid(), order_id uuid not null references orders(id) on delete cascade,
  restaurant_id uuid not null references restaurants(id) on delete cascade, dish_id uuid references dishes(id) on delete set null,
  dish_name text not null, unit_price numeric(12,2) not null check (unit_price >= 0), quantity int not null check (quantity between 1 and 99),
  line_total numeric(12,2) not null check (line_total >= 0)
);
alter table menu_visits enable row level security; alter table orders enable row level security; alter table order_items enable row level security;
drop policy if exists "owner_menu_visits" on menu_visits; create policy "owner_menu_visits" on menu_visits for select using (restaurant_id in (select id from restaurants where owner_id = auth.uid()));
drop policy if exists "owner_orders" on orders; create policy "owner_orders" on orders for all using (restaurant_id in (select id from restaurants where owner_id = auth.uid())) with check (restaurant_id in (select id from restaurants where owner_id = auth.uid()));
drop policy if exists "owner_order_items" on order_items; create policy "owner_order_items" on order_items for select using (restaurant_id in (select id from restaurants where owner_id = auth.uid()));
create index if not exists menu_visits_restaurant_created_idx on menu_visits (restaurant_id, created_at desc);
create index if not exists orders_restaurant_created_idx on orders (restaurant_id, created_at desc);
create index if not exists orders_restaurant_status_idx on orders (restaurant_id, status);
create index if not exists order_items_order_idx on order_items (order_id);
create index if not exists order_items_restaurant_dish_idx on order_items (restaurant_id, dish_id);
