'use client'
import { FormEvent, useEffect, useState } from 'react'
import { useRouter } from 'next/navigation'
import { createPortal } from 'react-dom'
type Employee={id:string;full_name:string;employee_code:string;photo_url?:string}
export default function EmployeePhotoManager({employees}:{employees:Employee[]}){const router=useRouter(),[open,setOpen]=useState(false),[employeeId,setEmployeeId]=useState(''),[file,setFile]=useState<File|null>(null),[preview,setPreview]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[addForm,setAddForm]=useState<Element|null>(null);const selected=employees.find(x=>x.id===employeeId)
 function choose(next:File|null,isNew=false){setFile(next);setPreview(next?URL.createObjectURL(next):'');if(isNew)window.dispatchEvent(new CustomEvent('employee-photo-selected',{detail:next}))}
 useEffect(()=>{const inspect=()=>{const form=document.querySelector('.ems-modal form,.employee-modal form');setAddForm(form?.querySelector('h2')?.textContent==='Add Employee'?form:null)};const observer=new MutationObserver(inspect);observer.observe(document.body,{childList:true,subtree:true});inspect();return()=>observer.disconnect()},[])
 useEffect(()=>{const click=(event:Event)=>{const person=(event.target as HTMLElement).closest('.employee-person,.ems-table .person');const name=person?.querySelector('b')?.textContent,match=employees.find(x=>x.full_name===name);if(match&&(event.target as HTMLElement).closest('img,i')){setEmployeeId(match.id);setPreview('');setFile(null);setOpen(true)}};document.addEventListener('click',click);return()=>document.removeEventListener('click',click)},[employees])
 async function upload(event:FormEvent){event.preventDefault();if(!file)return;setBusy(true);const form=new FormData();form.set('employeeId',employeeId);form.set('photo',file);const response=await fetch('/api/employees/photo',{method:'POST',body:form});const result=await response.json().catch(()=>({}));if(!response.ok){setError(result.error||'Upload failed.');setBusy(false);return}setOpen(false);setBusy(false);router.refresh()}
 const field=addForm?createPortal(<div className="employee-photo-inline"><div className="employee-photo-preview">{preview?<img src={preview} alt="Preview"/>:<span>♙</span>}</div><label className="employee-photo-picker">Employee photo <span>(optional)</span><input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>choose(e.target.files?.[0]||null,true)}/><small>JPG, PNG or WebP · maximum 3 MB</small></label></div>,addForm):null
 return <>{field}{open&&<div className="employee-modal employee-photo-modal"><form onSubmit={upload}><header><h2>Replace Employee Photo</h2><button type="button" onClick={()=>setOpen(false)}>×</button></header><p className="employee-photo-name">{selected?.full_name}</p><div className="employee-photo-preview">{preview||selected?.photo_url?<img src={preview||selected?.photo_url} alt="Preview"/>:<span>♙</span>}</div><label className="employee-photo-picker">Choose new photo<input required type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>choose(e.target.files?.[0]||null)}/><small>Maximum 3 MB</small></label>{error&&<p className="customer-order-error">{error}</p>}<button className="employee-modal-save" disabled={busy||!file}>{busy?'Uploading…':'Replace photo'}</button></form></div>}</>}
