import { createRateLimiter, clientIp } from '@/lib/request-security'
import { rejectUnsafeRequest } from '@/lib/menu-api'
import { readJsonBody } from '@/lib/request-security'
import { NextResponse } from 'next/server'
import { supabaseAdmin } from '@/lib/supabase'

const datePattern=/^\d{4}-\d{2}-\d{2}$/
const rateLimited = createRateLimiter(8)
export async function POST(request:Request){
  const unsafe = rejectUnsafeRequest(request); if (unsafe) return unsafe
  if (rateLimited(clientIp(request))) return NextResponse.json({ error: 'Too many requests. Please try again later.' }, { status: 429 })
const origin=request.headers.get('origin');if(origin&&origin!==new URL(request.url).origin)return NextResponse.json({error:'Invalid request origin.'},{status:403});const body=(await readJsonBody(request) ?? {}),reason=typeof body?.reason==='string'?body.reason.trim().replace(/\s+/g,' '):'',name=typeof body?.name==='string'?body.name.trim().replace(/\s+/g,' '):'',code=typeof body?.employeeCode==='string'?body.employeeCode.trim().toUpperCase():'',phone=typeof body?.phone==='string'?body.phone.trim().replace(/\D/g,''):'';if(!/^[a-z0-9-]{3,50}$/.test(body?.slug||'')||name.length<2||name.length>120||!(/^[A-Z0-9-]{2,30}$/.test(code))||!['annual','sick','casual','unpaid'].includes(body?.leaveType)||!datePattern.test(body?.startsOn||'')||!datePattern.test(body?.endsOn||'')||body.endsOn<body.startsOn||reason.length<3||reason.length>400)return NextResponse.json({error:'Please provide valid employee and leave details.'},{status:400});if(!process.env.SUPABASE_SERVICE_ROLE_KEY)return NextResponse.json({error:'Leave portal is not configured.'},{status:503});const admin=supabaseAdmin();const{data:restaurant}=await admin.from('restaurants').select('id').eq('slug',body.slug).eq('is_active',true).maybeSingle();if(!restaurant)return NextResponse.json({error:'Restaurant leave portal not found.'},{status:404});const{data:employee}=await admin.from('employees').select('id,restaurant_id,full_name,phone,status').eq('restaurant_id',restaurant.id).eq('employee_code',code).neq('status','inactive').maybeSingle();const storedPhone=(employee?.phone||'').replace(/\D/g,'');if(!employee||employee.full_name.toLowerCase()!==name.toLowerCase()||(storedPhone&&storedPhone!==phone))return NextResponse.json({error:'Employee details do not match our records.'},{status:403});const{data:overlap}=await admin.from('leave_requests').select('id').eq('employee_id',employee.id).in('status',['pending','approved']).lte('starts_on',body.endsOn).gte('ends_on',body.startsOn).limit(1);if(overlap?.length)return NextResponse.json({error:'A pending or approved leave request already overlaps these dates.'},{status:409});const{data,error}=await admin.from('leave_requests').insert({restaurant_id:employee.restaurant_id,employee_id:employee.id,leave_type:body.leaveType,starts_on:body.startsOn,ends_on:body.endsOn,reason,status:'pending'}).select('id').single();if(error)return NextResponse.json({error:'Could not submit the leave request.'},{status:503});return NextResponse.json({requestId:data.id},{status:201})}
